### ISSUE TITLE
Blacklisting Still Broken?

### ISSUE THREAD

**Issue by JTEclipse** [pmdevita/StayPut#18]
I'm not in any way the best understander of code, but from what I take it, I've added in the proper lines to blacklist worlds, and it still doesn't work. I also noticed that **issue #10** Hasn't been updated, and has been acknowledged as a bug. Is there any progress towards finishing it yet?

 
![blacklistissue](https://user-images.githubusercontent.com/109827395/180567295-784a92f1-bdd4-4250-9340-affbc708547c.png)
 If I've done it wrong, I'd like to know, but in the same breath, is there any progress towards fixing this? 
 
 Otherwise the plugin is great.
 
 Thanks
 ~ Eclipse

**Comment by pmdevita** [comment]
I've been mostly focusing the database fixes (try 2.0.0 if you haven't yet!) so I haven't really looked at that. From just glancing at the code, nothing looks wrong. I'll have to test that and figure out what's wrong when I do the full 2.0.0 release.

The blacklisting is supposed to prevent a location from being saved for a world, so when you return to it, it should send you to spawn. Is it keeping track of your location in this world?

Also, just a bit of etiquette, generally on GitHub, if an issue already exists for a bug or feature, it's better to comment on it then open a new one since it keeps things organized.

**Comment by pmdevita** [comment]
2.1.0 will now print the blacklisted world list in debug mode, that should help narrow down the problem if it's still occurring.
