### ISSUE TITLE
Missing dependencies?

### ISSUE THREAD

**Issue by SlimeDog** [pmdevita/StayPut#4]
Spigot 1.15.2
StayPut 1.2 (the second one)

On start-up
```
[11:27:49] [Server thread/WARN]: [StayPut] Loaded class com.onarandombox.MultiversePortals.event.MVPortalEvent from Multiverse-Portals v4.1.1-SNAPSHOT-b808 which is not a depend, softdepend or loadbefore of this plugin.
[11:27:49] [Server thread/WARN]: [StayPut] Loaded class org.slf4j.LoggerFactory from V10Lift v0.5.7 which is not a depend, softdepend or loadbefore of this plugin.
```
- Should Multiverse-Portals be added to dependencies? Does StayPut depend on it? I see it is included in the POM.
- Does LoggerFactory need to br shaded in (I'm sure StayPut doesn't depend on V10Lift)?

**Comment by pmdevita** [comment]
It was shading the entire multiverse portals plugin into the jar so I excluded it. Guess I didn't see that when I tested it, let me see what I can do

**Comment by SlimeDog** [comment]
Thanks.

**Comment by pmdevita** [comment]
Are you using MV Portals on your server?

**Comment by SlimeDog** [comment]
Spigot 1.15.2 as stated above. And I am running MV-Portals 4.1.1 as indicated above. Otherwise, SP would not be able to load MVPortalEvent from it.

**Comment by pmdevita** [comment]
StayPut checks for the existence of the MV Portals before attaching event handlers so it can maintain compatibility with and without.

I think I was able to fix it, how's this?
[StayPut-1.2-SNAPSHOT.zip](https://github.com/pmdevita/StayPut/files/4569368/StayPut-1.2-SNAPSHOT.zip)

**Comment by SlimeDog** [comment]
Confirmed that adding the soft depend for MV-Portals resolves that issue. The LoggerFactory issue remains.

**Comment by pmdevita** [comment]
That LoggerFactory one is quite puzzling to me, I'm not referencing anything from the V10Lift plugin and I'm not importing org.slf4j.LoggerFactory. I guess I'll try throwing the V10Lift plugin into my test server and see what happens

**Comment by SlimeDog** [comment]
I know SP is not referencing V10Lift. I expect that it is referencing (something in) LoggerFactory.

**Comment by mart-r** [comment]
> It was shading the entire multiverse portals plugin into the jar so I excluded it. Guess I didn't see that when I tested it, let me see what I can do

It appears you've not pushed the changes yet, but I hope you simply set the scope to provided on the specific dependency (in a similar manner to the spigot api dependency).



> That LoggerFactory one is quite puzzling to me, I'm not referencing anything from the V10Lift plugin and I'm not importing org.slf4j.LoggerFactory. I guess I'll try throwing the V10Lift plugin into my test server and see what happens

So here's the deal.
V10Lift jar includes the org.slf4j.LoggerFactory class (its shaded through the [direct dependency](https://github.com/stijnb1234/V10Lift2/blob/master/pom.xml) of SBUtilities with [pom](https://nexus.iobyte.nl/repository/maven-public/nl/SBDevelopment/SBUtilities/1.9/SBUtilities-1.9.pom) - I don't really see where it gets shaded into this, but when you open the jar, it's there).
Your plugin shades ormlite, which uses it [here](https://github.com/j256/ormlite-core/blob/master/src/main/java/com/j256/ormlite/logger/Slf4jLoggingLog.java).
Now, when the ORMlite stuff in your plugin attempts to access this class, it turns out it was originally loaded by V10Lift, which is why there's a warning about this.

PS: I'm pretty sure they added the warning in 1.15, so it won't be present in lower versions. The idea is to clearly expose dependencies.

**Comment by pmdevita** [comment]
Ah setting them to provided makes more sense, thanks. 

Thanks for pointing out LoggerFactory in ormlite. I'm guessing I should try to shade in the logging library for it then? Or since the library seems to be optional should I block it somehow?

**Comment by pmdevita** [comment]
Looked into how logging worked in ormlite, figured out it used several different log libraries depending on what was available and figured out how to force it to use the internal logger. Now it no longer loads the slf4j logging library when paired with V10Lift (and potentially any other plugin including it).

**Comment by SlimeDog** [comment]
So much better. Good work.

**Comment by pmdevita** [comment]
Thank you!
